@echo off
echo 🏗️ Building Angeh Project...
echo 🔨 Compiling .angeh files to Quantum Bytecode...
python run_pure_angeh_ide.py --build
echo.
echo 📦 Packaging Resources...
echo.
echo ✅ BUILD SUCCESSFUL.
